const mongoose = require('mongoose');
const Schema   = mongoose.Schema;

const logsSchema = new Schema({
    _id         : {type : String, required: true},  // Unique Id of log must be generated by ObjectID() to ensure unique
    uniqRefId   : {type : String, required: true},  // Hash of _id -> can be sent to client
    msgRefId    : {type : String, "default": ""},   // Reference/Transaction/Txn Id of Transaction log if present in message.
    genUserId   : {type : String, required: true},  // UID of the person on which this is transaction was generated
    boolPersonal: {type : Boolean,required: true},  // Boolean to check if this transaction is personal or between 2 users.
    secUsername : {type : String, "default": ""},   // If this transaction is between two friends
    title       : {type : String, required: true},  // Title to be shown on the user's dashboard
    amount      : {type : Number, required: true},  // Amount credited/Paid -> (-ve), debited/Received -> (+ve)
    completeLog : {type : String, required: true}   // Complete message as it is
});

const Logs = mongoose.model('logs', logsSchema);
module.exports = Logs;